### ISSUE TITLE
Validation group with options throws ArgumentError

### ISSUE THREAD

**Issue by mogelbrod** [adzap/grouped_validations#1]
Passing a condition for the options argument results in an ArgumentError (`wrong number of arguments (2 for 1)`). This happens on Rails 3.0.5, using v0.2.2 of the gem.

```
validation_group :address, :if => address_required? do
    validates :address, :postal_number, :postal_address, :presence => true
end

def address_required?
    true
end
```

**Comment by adzap** [comment]
The feature is actually not in a released gem yet. I had updated the readme before releasing the gem. Sorry for the confusion.

**Comment by mogelbrod** [comment]
Ah, too bad. Do you by any chance have an ETA on when it might be included? :)
Thanks for the response!

**Comment by adzap** [comment]
it's released!
